version: '{build}'
environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
install:
  # avoid warnings which could also be suppressed with --no-warn-script-location
  - set "PATH=%PYTHON%\Scripts;%PATH%"
  - "%PYTHON%\\python.exe -m pip install -U setuptools"
  # install_requires
  - "%PYTHON%\\python.exe -m pip install -U coloredlogs distlib EmPy"
  # tests_require, additionally mock
  - "%PYTHON%\\python.exe -m pip install -U flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-quotes mock pep8-naming pylint pytest pytest-cov scspell3k"
  # for uploading the coverage information to codecov
  - "%PYTHON%\\python.exe -m pip install -U codecov"
build: off
test_script:
  # invoke pytest
  - "%PYTHON%\\python.exe -m pytest --cov=colcon_core --cov-report=xml:coverage.xml --cov-branch"
on_success:
  - "%PYTHON%\\python.exe -m codecov --file coverage.xml -X gcov"
